---
name         : puppetmaster
hostname     : puppet.arthurjames.vagrant
aliases:
  - puppet
  - puppetmaster
  - puppetdb
box          : vagrant-debian-wheezy
ram          : 2048
cpus         : 2
ip           : 10.0.11.2
